[server]
maxUploadSize = 20
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#24734b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f5f2"
textColor = "#183429"
